[package]
name = "risq"
version = "0.1.0"
authors = ["Justin Carter <justin@misthos.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "*"
actix-web = "*"
bitcoin = "0.18.2"
bitcoin_hashes = "0.7"
bufstream = "0.1.3"
bytes = "*"
env_logger = "*"
futures = "*"
log = "*"
prost = "0.5.*"
prost-types = "*"
rand = "0.7.1"
tokio = "*"
socks = "0.3.2"

[build-dependencies]
prost-build = "*"
