[package]
name = "risq"
version = "0.1.0"
authors = ["Justin Carter <justin@misthos.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socks = "0.3.2"
bufstream = "0.1.3"
futures = "0.1.29"
rand = "0.7.1"
bitcoin = "0.18.2"
bitcoin_hashes = "0.7"
