[package]
name = "risq"
version = "0.0.1"
authors = ["Justin Carter <justin@misthos.io>"]
edition = "2018"
license = "AGPL-3.0"
repository = "https://github.com/bodymindarts/risq"
description = "Re-implementation of Bisq (https://github.com/bisq-network/bisq) in rust"

[features]
default = []

all = ["checker", "statistics"]
checker = []
statistics = []

[dependencies]
actix = "*"
actix-web = "*"
bitcoin = "*"
bitcoin_hashes = "0.7.0"
bufstream = "*"
bytes = "*"
dirs = "*"
env_logger = "*"
either = "*"
futures = "*"
futures-locks = "*"
juniper = { version = "*"}
juniper-from-schema = { version = "*"}
lazy_static = "*"
log = "*"
prost = "*"
prost-types = "*"
rand = "0.7.2"
reqwest = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
socks = "*"
tokio = "*"
uuid = { version = "*", features = ["v4"] }

[dependencies.clap]
version = "*"
features = [ "suggestions", "color", "unstable"] 

[build-dependencies]
prost-build = "*"
