[package]
name = "risq"
version = "0.1.0"
authors = ["Justin Carter <justin@misthos.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
checker = []
statistics = []

[dependencies]
actix = "*"
actix-web = "*"
bitcoin = "*"
bitcoin_hashes = "*"
bufstream = "*"
bytes = "*"
dirs = "*"
env_logger = "*"
either = "*"
futures = "*"
futures-locks = "*"
juniper = { version = "*"}
juniper-from-schema = { version = "*"}
lazy_static = "*"
log = "*"
prost = "*"
prost-types = "*"
rand = "*"
reqwest = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
socks = "*"
tokio = "*"
uuid = { version = "*", features = ["v4"] }

[dependencies.clap]
version = "*"
features = [ "suggestions", "color", "unstable"] 

[build-dependencies]
prost-build = "*"
