[package]
name = "risq"
version = "0.1.0"
authors = ["Justin Carter <justin@misthos.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "*"
actix-web = "*"
bitcoin = "*"
bitcoin_hashes = "*"
bufstream = "*"
bytes = "*"
env_logger = "*"
futures = "*"
lazy_static = "*"
log = "*"
prost = "*"
prost-types = "*"
rand = "*"
socks = "*"
tokio = "*"
uuid = { version = "*", features = ["v4"] }

[build-dependencies]
prost-build = "*"
