pub enum Type {
    Fiat,
    Crypto,
}

pub struct Currency {
    pub code: &'static str,
    pub name: &'static str,
    pub precision: u16,
    pub currency_type: Type,
}

pub fn all() -> &'static [Currency] {
    &ALL
}

const ALL: [Currency; 249] = [
    Currency {
        code: "ACM",
        name: "Actinium",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "ADE",
        name: "Adeptio",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "AED",
        name: "United Arab Emirates Dirham",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "AEON",
        name: "Aeon",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "AEUR",
        name: "Augmint Euro",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "AFN",
        name: "Afghan Afghani",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "ALL",
        name: "Albanian Lek",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "AMD",
        name: "Armenian Dram",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "AMIT",
        name: "Amitycoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "ANG",
        name: "Netherlands Antillean Guilder",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "AOA",
        name: "Angolan Kwanza",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "ARQ",
        name: "Arqma",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "ARS",
        name: "Argentine Peso",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "ASK",
        name: "Askcoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "AUD",
        name: "Australian Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "AUS",
        name: "Australiacash",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "AWG",
        name: "Aruban Florin",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "AZN",
        name: "Azerbaijani Manat",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "BAM",
        name: "Bosnia-Herzegovina Convertible Mark",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "BBD",
        name: "Barbadian Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "BDT",
        name: "Bangladeshi Taka",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "BEAM",
        name: "Beam",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "BGN",
        name: "Bulgarian Lev",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "BHD",
        name: "Bahraini Dinar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "BIF",
        name: "Burundian Franc",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "BLUR",
        name: "Blur",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "BMD",
        name: "Bermudan Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "BND",
        name: "Brunei Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "BOB",
        name: "Bolivian Boliviano",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "BRL",
        name: "Brazilian Real",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "BSD",
        name: "Bahamian Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "BSQ",
        name: "BSQ",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "BTC",
        name: "Bitcoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "BTM",
        name: "Bitmark",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "BTN",
        name: "Bhutanese Ngultrum",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "BWP",
        name: "Botswanan Pula",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "BYN",
        name: "Belarusian Ruble",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "BZC",
        name: "Bitzec",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "BZD",
        name: "Belize Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "CAD",
        name: "Canadian Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "CASH2",
        name: "Cash2",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "CDF",
        name: "Congolese Franc",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "CHA",
        name: "Chaucha",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "CHF",
        name: "Swiss Franc",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "CLOAK",
        name: "CloakCoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "CLP",
        name: "Chilean Peso",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "CNY",
        name: "Chinese Yuan",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "COP",
        name: "Colombian Peso",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "CRC",
        name: "Costa Rican Col\u{00f3}n",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "CRCL",
        name: "CRowdCLassic",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "CRDS",
        name: "Credits",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "CROAT",
        name: "Croat",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "CUP",
        name: "Cuban Peso",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "CVE",
        name: "Cape Verdean Escudo",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "CZK",
        name: "Czech Republic Koruna",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "DAI",
        name: "Dai Stablecoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "DARX",
        name: "BitDaric",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "DASH",
        name: "Dash",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "DCR",
        name: "Decred",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "DJF",
        name: "Djiboutian Franc",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "DKK",
        name: "Danish Krone",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "DOGE",
        name: "Dogecoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "DOI",
        name: "Doichain",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "DOP",
        name: "Dominican Peso",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "DRGL",
        name: "Dragonglass",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "DST",
        name: "DSTRA",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "DXO",
        name: "Dextro",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "DZD",
        name: "Algerian Dinar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "EGP",
        name: "Egyptian Pound",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "ERN",
        name: "Eritrean Nakfa",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "ETB",
        name: "Ethiopian Birr",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "ETC",
        name: "Ether Classic",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "ETH",
        name: "Ether",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "ETHS",
        name: "EtherStone",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "EUR",
        name: "Euro",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "FJC",
        name: "Fujicoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "FJD",
        name: "Fijian Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "FKP",
        name: "Falkland Islands Pound",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "FRTY",
        name: "FourtyTwo",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "GALI",
        name: "Galilel",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "GBP",
        name: "British Pound",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "GBYTE",
        name: "Byte",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "GEL",
        name: "Georgian Lari",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "GHS",
        name: "Ghanaian Cedi",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "GIP",
        name: "Gibraltar Pound",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "GMCN",
        name: "GambleCoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "GMD",
        name: "Gambian Dalasi",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "GNF",
        name: "Guinean Franc",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "GRIN",
        name: "Grin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "GTQ",
        name: "Guatemalan Quetzal",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "GYD",
        name: "Guyanaese Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "HATCH",
        name: "Hatch",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "HKD",
        name: "Hong Kong Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "HLM",
        name: "Helium",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "HNL",
        name: "Honduran Lempira",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "HRK",
        name: "Croatian Kuna",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "HTG",
        name: "Haitian Gourde",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "HUF",
        name: "Hungarian Forint",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "IDA",
        name: "IdaPay",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "IDR",
        name: "Indonesian Rupiah",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "ILS",
        name: "Israeli New Sheqel",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "INR",
        name: "Indian Rupee",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "IQD",
        name: "Iraqi Dinar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "IRD",
        name: "Iridium",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "IRR",
        name: "Iranian Rial",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "ISK",
        name: "Icelandic Kr\u{00f3}na",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "JMD",
        name: "Jamaican Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "JOD",
        name: "Jordanian Dinar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "JPY",
        name: "Japanese Yen",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "KEK",
        name: "Kekcoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "KES",
        name: "Kenyan Shilling",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "KGS",
        name: "Kyrgystani Som",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "KHR",
        name: "Cambodian Riel",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "KMF",
        name: "Comorian Franc",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "KPW",
        name: "North Korean Won",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "KRW",
        name: "South Korean Won",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "KWD",
        name: "Kuwaiti Dinar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "KYD",
        name: "Cayman Islands Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "KZT",
        name: "Kazakhstani Tenge",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "LAK",
        name: "Laotian Kip",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "LBP",
        name: "Lebanese Pound",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "LCP",
        name: "LitecoinPlus",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "LKR",
        name: "Sri Lankan Rupee",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "LRD",
        name: "Liberian Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "LSL",
        name: "Lesotho Loti",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "LTC",
        name: "Litecoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "LTZ",
        name: "LitecoinZ",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "LYD",
        name: "Libyan Dinar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "LYTX",
        name: "Lytix",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "MAD",
        name: "Moroccan Dirham",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "MAI",
        name: "Starwels",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "MASK",
        name: "Mask",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "MBGL",
        name: "MobitGlobal",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "MDL",
        name: "Moldovan Leu",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "MGA",
        name: "Malagasy Ariary",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "MILE",
        name: "Mile",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "MKD",
        name: "Macedonian Denar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "MMK",
        name: "Myanmar Kyat",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "MNT",
        name: "Mongolian Tugrik",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "MOP",
        name: "Macanese Pataca",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "MOX",
        name: "MoX",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "MQX",
        name: "MirQuiX",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "MRO",
        name: "Mauritanian Ouguiya",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "MUE",
        name: "MonetaryUnit",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "MUR",
        name: "Mauritian Rupee",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "MVR",
        name: "Maldivian Rufiyaa",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "MWK",
        name: "Malawian Kwacha",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "MXN",
        name: "Mexican Peso",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "MYR",
        name: "Malaysian Ringgit",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "MZN",
        name: "Mozambican Metical",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "NAD",
        name: "Namibian Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "NAV",
        name: "Navcoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "NEOS",
        name: "Neos",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "NGN",
        name: "Nigerian Naira",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "NIO",
        name: "Nicaraguan C\u{00f3}rdoba",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "NMC",
        name: "Namecoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "NOK",
        name: "Norwegian Krone",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "NOR",
        name: "Noir",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "NPR",
        name: "Nepalese Rupee",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "NZD",
        name: "New Zealand Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "OMR",
        name: "Omani Rial",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "ONION",
        name: "DeepOnion",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "PAB",
        name: "Panamanian Balboa",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "PEN",
        name: "Peruvian Nuevo Sol",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "PGK",
        name: "Papua New Guinean Kina",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "PHP",
        name: "Philippine Peso",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "PINK",
        name: "Pinkcoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "PIVX",
        name: "PIVX",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "PKR",
        name: "Pakistani Rupee",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "PLE",
        name: "Plenteum",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "PLN",
        name: "Polish Zloty",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "PRSN",
        name: "Persona",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "PYG",
        name: "Paraguayan Guarani",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "PZDC",
        name: "PZDC",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "QAR",
        name: "Qatari Rial",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "QBS",
        name: "Qbase",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "QMCoin",
        name: "QMCoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "QWC",
        name: "Qwertycoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "RADS",
        name: "Radium",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "RMX",
        name: "Remix",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "RON",
        name: "Romanian Leu",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "RSD",
        name: "Serbian Dinar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "RUB",
        name: "Russian Ruble",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "RWF",
        name: "Rwandan Franc",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "RYO",
        name: "Ryo",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "SAR",
        name: "Saudi Riyal",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "SBD",
        name: "Solomon Islands Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "SCP",
        name: "SiaPrimeCoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "SCR",
        name: "Seychellois Rupee",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "SDG",
        name: "Sudanese Pound",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "SEK",
        name: "Swedish Krona",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "SF",
        name: "Siafund",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "SGD",
        name: "Singapore Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "SHP",
        name: "St. Helena Pound",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "SLL",
        name: "Sierra Leonean Leone",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "SOS",
        name: "Somali Shilling",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "SPACE",
        name: "SpaceCash",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "SRD",
        name: "Surinamese Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "SSP",
        name: "South Sudanese Pound",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "STN",
        name: "S\u{00e3}o Tom\u{00e9} and Pr\u{00ed}ncipe Dobra",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "SUB1X",
        name: "SUB1X",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "SVC",
        name: "Salvadoran Col\u{00f3}n",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "SYP",
        name: "Syrian Pound",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "SZL",
        name: "Swazi Lilangeni",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "THB",
        name: "Thai Baht",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "TJS",
        name: "Tajikistani Somoni",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "TMT",
        name: "Turkmenistani Manat",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "TND",
        name: "Tunisian Dinar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "TOP",
        name: "Tongan Pa\u{02bb}anga",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "TRTL",
        name: "TurtleCoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "TRY",
        name: "Turkish Lira",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "TTD",
        name: "Trinidad & Tobago Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "TUSD",
        name: "TrueUSD",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "TWD",
        name: "New Taiwan Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "TZS",
        name: "Tanzanian Shilling",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "UAH",
        name: "Ukrainian Hryvnia",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "UCC",
        name: "UnitedCommunityCoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "UGX",
        name: "Ugandan Shilling",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "UNO",
        name: "Unobtanium",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "USD",
        name: "US Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "USDC",
        name: "USD Coin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "UYU",
        name: "Uruguayan Peso",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "UZS",
        name: "Uzbekistani Som",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "VEF",
        name: "Venezuelan Bol\u{00ed}var",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "VEIL",
        name: "Veil",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "VND",
        name: "Vietnamese Dong",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "VUV",
        name: "Vanuatu Vatu",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "VXV",
        name: "VectorspaceAI",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "WEB",
        name: "Webchain",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "WRKZ",
        name: "WrkzCoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "WST",
        name: "Samoan Tala",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "XAF",
        name: "Central African CFA Franc",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "XCD",
        name: "East Caribbean Dollar",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "XCP",
        name: "Counterparty",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "XDR0",
        name: "XDR",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "XMR",
        name: "Monero",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "XOF",
        name: "West African CFA Franc",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "XPF",
        name: "CFP Franc",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "XRC",
        name: "Bitcoin Rhodium",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "XSPEC",
        name: "Spectrecoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "XZC",
        name: "Zcoin",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "YER",
        name: "Yemeni Rial",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "ZAR",
        name: "South African Rand",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "ZEC",
        name: "Zcash",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "ZEL",
        name: "ZelCash",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "ZEN",
        name: "Horizen",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "ZER",
        name: "Zero",
        precision: 8,
        currency_type: Type::Crypto,
    },
    Currency {
        code: "ZMW",
        name: "Zambian Kwacha",
        precision: 8,
        currency_type: Type::Fiat,
    },
    Currency {
        code: "ZWL",
        name: "Zimbabwean Dollar (2009)",
        precision: 8,
        currency_type: Type::Fiat,
    },
];
