#!/bin/bash

REPO_ROOT_DIR="$(dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd ))"

tor_data_dir=${REPO_ROOT_DIR}/.tor
pid_file=${tor_data_dir}/pid

if [[ -f ${pid_file} ]]; then
  echo "Killing running tor"
  kill -s 9 $(cat ${pid_file})
fi

rm -rf ${tor_data_dir}
mkdir -p ${tor_data_dir}

cat ${REPO_ROOT_DIR}/.torrc | sed "s#((TOR_ROOT))#${tor_data_dir}#" > ${tor_data_dir}/torrc
tor --DataDirectory ${tor_data_dir} -f ${tor_data_dir}/torrc
