#!/bin/bash

set -e

if [[ $(which spruce) == "" ]]; then
  echo "You will need to install spruce to repipe. https://github.com/geofffranks/spruce/releases"
  exit 1
fi

target="${FLY_TARGET:-misthos}"

REPO_ROOT_DIR="$(dirname $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd ))"

TMPDIR=""¬
TMPDIR=$(mktemp -d -t repipe.XXXXXX)
trap "rm -rf ${TMPDIR}" INT TERM QUIT EXIT

spruce merge --prune meta ${REPO_ROOT_DIR}/ci/pipeline.yml ${REPO_ROOT_DIR}/ci/settings.yml > ${TMPDIR}/pipeline.yml

echo "Updating pipeline @ ${target}"

fly -t ${target} set-pipeline -p risq -c ${TMPDIR}/pipeline.yml
fly -t ${target} unpause-pipeline -p risq
